# Sharpe Rolling optimizado

In [1]:
import pandas as pd
import numpy as np
from time import time
from timeit import timeit
window = 10

In [2]:
tiempo_inicial = time()

# Cargamos los datos y extraemos por un lado los activos, la renta fija y el índice Dax
datos=pd.read_csv('DAX.csv',sep=';')
activos=datos.drop(['Fecha', 'Dax', 'BUND'], 1) # Extraemos los activos quitando las últimas columnasy la primera.
BUND=datos.loc[:, 'BUND'] # Extraemos la renta fija.

# Generamos las matrices de datos donde guardaremos los resultados.
rent_activos=pd.DataFrame(np.zeros((activos.shape[0] , activos.shape[1])), index=activos.index, columns=activos.columns)
rent_bund=pd.DataFrame(np.zeros(len(BUND)))
sharpe_activos=pd.DataFrame(np.zeros((activos.shape[0] , activos.shape[1])), index=activos.index, columns=activos.columns)

# Calculamos la rentabilidad de los activos, renta fija e índice.
rent_activos = np.log(activos).diff()
rent_BUND = np.log(BUND).diff()
rent_activos.iloc[:1]=0
rent_BUND[0]=0
volatilidad=pd.DataFrame(np.zeros((activos.shape[0] , activos.shape[1])), index=activos.index, columns=activos.columns)

for activo in activos.columns:
    volatilidad.loc[:,activo] =(rent_activos.loc[:,activo].rolling(window).std())
    
volatilidad=volatilidad.fillna(0)
Rfactivos =pd.DataFrame(np.ones((rent_activos.shape[0] , rent_activos.shape[1])), index=rent_activos.index, columns=rent_activos.columns)
rent_BUND = Rfactivos.mul(rent_BUND, axis=0)
sharpe_activos = (rent_activos - rent_BUND) / volatilidad
sharpe_activos.replace([np.inf, -np.inf], np.nan, inplace = True)
sharpe_activos = sharpe_activos.fillna(0)
tiempo_final = time() 
tiempo_ejecucion = tiempo_final - tiempo_inicial

print ('El tiempo de ejecucion fue:',tiempo_ejecucion )

sharpe_activos.head(20)

El tiempo de ejecucion fue: 0.04796791076660156

,Adidas,Allianz,Basf,Bayer,BEIERSDORF,BMW,COMMERZBANK,DAIMLER,DEUTSCHE BANK,DEUTSCHE BOERSE,...,LINDE,MAN,MERCK,METRO,MUNICHRE,RWE,SAP,SIEMENS,THYSSENKRUPP,VOLKSWAGEN
0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.609137,0.380755,0.0,0.328525,0.384848,-0.432359,-0.277207,-0.038051,0.562302,0.930956,...,-0.068541,0.662089,-0.566186,-0.299272,-0.063761,1.332739,0.119737,0.000000,0.201782,0.087783
10,-0.720453,-0.403682,0.0,-0.679324,0.006195,-1.165642,-0.112814,-0.389309,-0.883829,-2.698901,...,0.680168,1.189170,-0.191764,-0.588584,-0.825083,0.173411,-0.469389,0.000000,0.834374,-0.468594
11,0.724809,0.394676,0.0,0.788138,-0.416513,0.219918,0.204097,0.563287,0.924049,1.756120,...,0.760909,-0.991082,0.940011,0.535079,-0.402833,0.894959,-0.516313,-3.256685,0.725153,2.503887
12,-2.981520,-2.577262,0.0,-3.133217,-0.781650,-1.429349,-1.839397,-2.137320,-2.817176,-0.206688,...,-1.832818,-2.046909,-1.290995,-3.106233,-2.650498,-2.319661,-1.594748,-3.356825,-2.001001,-2.027930
13,1.154836,-1.380132,0.0,1.225588,0.249226,0.722703,-0.161158,-0.079229,-0.048646,-0.136517,...,0.450964,1.289160,0.360214,0.954918,-0.465468,0.901904,-0.534017,0.167788,0.507368,0.348806
14,-0.536863,-0.118224,0.0,-0.527802,0.289300,0.284266,-1.447448,-0.390382,-0.631345,-0.519868,...,-0.634030,1.422608,-0.896599,-0.700546,-0.797424,-0.292276,-0.134499,0.374586,0.049474,-0.292974
15,-0.534765,-1.068394,0.0,-0.918075,-1.770761,-1.282864,1.572473,-0.597548,-0.692181,-0.455595,...,-1.684447,-0.816855,-0.615627,-1.871597,-1.788361,-0.927932,0.418726,-0.969648,-1.135154,-0.847416
16,-1.160772,-0.441812,0.0,0.224614,-2.901815,-2.077668,-1.718106,-0.658306,0.030761,-0.469886,...,-0.797263,-1.848283,0.390939,0.002834,-0.789122,-1.102753,1.239839,1.605712,-0.660821,-0.698525
17,-0.472052,-1.344979,0.0,-0.940321,-2.232757,-0.728177,-0.264227,-0.527970,-1.186240,0.110374,...,-1.774584,-0.150360,0.966999,0.111369,-1.634585,-0.382384,-1.903335,-2.067034,-0.450081,-0.564004
18,-0.986913,-2.020038,0.0,-0.688480,-1.482707,0.329981,-1.069488,-0.795302,-0.677945,-0.842492,...,-1.418366,-0.570368,-1.076978,-2.273103,-3.019124,-0.471459,-0.105102,-0.850317,-0.905563,0.059131
19,0.283632,-0.120210,0.0,0.071230,0.510474,0.342002,-0.155552,0.616959,0.274994,-0.260207,...,-0.511770,0.577241,-1.431703,0.279284,-1.019027,0.747831,0.751156,0.140598,-0.011911,0.238773

## Otra manera de hacerlo

In [2]:
import pandas as pd
import numpy as np
import time

In [7]:
start_time = time.time()

filename = r'DAX.csv'
window = 10

# Read data and extract assets,bund(c[-1]),dax(c[-2])
pd_data = pd.read_csv(filename, header=0,
                      parse_dates=True, index_col=0, sep=';', dayfirst=True)

pd_data_log_ret_windowed = np.log(pd_data).diff()

rolling_var = np.log(pd_data).diff().rolling(window).std()

sharpe = pd_data_log_ret_windowed.iloc[:, :-1].add(
    pd_data_log_ret_windowed.iloc[:, -1].mul(
        -1, axis='index'), axis='index').div(
    rolling_var.iloc[:, :-1], axis='index')

print("--- %s seconds ---" % (time.time() - start_time))

--- 0.15802931785583496 seconds ---

In [8]:
sharpe.head(15)

,Adidas,Allianz,Basf,Bayer,BEIERSDORF,BMW,COMMERZBANK,DAIMLER,DEUTSCHE BANK,DEUTSCHE BOERSE,...,MAN,MERCK,METRO,MUNICHRE,RWE,SAP,SIEMENS,THYSSENKRUPP,VOLKSWAGEN,Dax
Fecha,,,,,,,,,,,,,,,,,,,,,
2003-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-01-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-01-15,-0.720453,-0.403682,-inf,-0.679324,0.006195,-1.165642,-0.112814,-0.389309,-0.883829,-2.698901,...,1.189170,-0.191764,-0.588584,-0.825083,0.173411,-0.469389,-inf,0.834374,-0.468594,0.500565
2003-01-16,0.724809,0.394676,-inf,0.788138,-0.416513,0.219918,0.204097,0.563287,0.924049,1.756120,...,-0.991082,0.940011,0.535079,-0.402833,0.894959,-0.516313,-3.256685,0.725153,2.503887,-0.732145
2003-01-17,-2.981520,-2.577262,-inf,-3.133217,-0.781650,-1.429349,-1.839397,-2.137320,-2.817176,-0.206688,...,-2.046909,-1.290995,-3.106233,-2.650498,-2.319661,-1.594748,-3.356825,-2.001001,-2.027930,-0.324774
2003-01-20,1.154836,-1.380132,-inf,1.225588,0.249226,0.722703,-0.161158,-0.079229,-0.048646,-0.136517,...,1.289160,0.360214,0.954918,-0.465468,0.901904,-0.534017,0.167788,0.507368,0.348806,-2.034606
2003-01-21,-0.536863,-0.118224,-inf,-0.527802,0.289300,0.284266,-1.447448,-0.390382,-0.631345,-0.519868,...,1.422608,-0.896599,-0.700546,-0.797424,-0.292276,-0.134499,0.374586,0.049474,-0.292974,-0.573093

## Otra manera de hacerlo

In [9]:
import pandas as pd
import numpy as np
import time
from tqdm import tqdm

In [10]:
start_time = time.time()

datos = pd.read_csv('DAX.csv', sep=';')
datos.set_index('Fecha', inplace=True)

ventana = 10

columns = datos.columns.tolist()
activos = datos[columns[:-2]]
BUND = datos[['BUND']]

rent_activos = np.log(activos).diff()
rent_BUND = np.log(BUND).diff()
volatilidad = rent_activos.rolling(ventana).var() ** 0.5
sharpe_activos = np.subtract(rent_activos, rent_BUND).iloc[ventana:] / volatilidad.iloc[ventana:]
sharpe_activos.replace([np.inf, -np.inf], 0, inplace=True)

print("--- %s seconds ---" % (time.time() - start_time))

--- 0.03100419044494629 seconds ---

In [11]:
sharpe_activos.head(15)

,Adidas,Allianz,Basf,Bayer,BEIERSDORF,BMW,COMMERZBANK,DAIMLER,DEUTSCHE BANK,DEUTSCHE BOERSE,...,LINDE,MAN,MERCK,METRO,MUNICHRE,RWE,SAP,SIEMENS,THYSSENKRUPP,VOLKSWAGEN
Fecha,,,,,,,,,,,,,,,,,,,,,
15/01/2003,-0.720453,-0.403682,0.0,-0.679324,0.006195,-1.165642,-0.112814,-0.389309,-0.883829,-2.698901,...,0.680168,1.189170,-0.191764,-0.588584,-0.825083,0.173411,-0.469389,0.000000,0.834374,-0.468594
16/01/2003,0.724809,0.394676,0.0,0.788138,-0.416513,0.219918,0.204097,0.563287,0.924049,1.756120,...,0.760909,-0.991082,0.940011,0.535079,-0.402833,0.894959,-0.516313,-3.256685,0.725153,2.503887
17/01/2003,-2.981520,-2.577262,0.0,-3.133217,-0.781650,-1.429349,-1.839397,-2.137320,-2.817176,-0.206688,...,-1.832818,-2.046909,-1.290995,-3.106233,-2.650498,-2.319661,-1.594748,-3.356825,-2.001001,-2.027930
20/01/2003,1.154836,-1.380132,0.0,1.225588,0.249226,0.722703,-0.161158,-0.079229,-0.048646,-0.136517,...,0.450964,1.289160,0.360214,0.954918,-0.465468,0.901904,-0.534017,0.167788,0.507368,0.348806
21/01/2003,-0.536863,-0.118224,0.0,-0.527802,0.289300,0.284266,-1.447448,-0.390382,-0.631345,-0.519868,...,-0.634030,1.422608,-0.896599,-0.700546,-0.797424,-0.292276,-0.134499,0.374586,0.049474,-0.292974
22/01/2003,-0.534765,-1.068394,0.0,-0.918075,-1.770761,-1.282864,1.572473,-0.597548,-0.692181,-0.455595,...,-1.684447,-0.816855,-0.615627,-1.871597,-1.788361,-0.927932,0.418726,-0.969648,-1.135154,-0.847416
23/01/2003,-1.160772,-0.441812,0.0,0.224614,-2.901815,-2.077668,-1.718106,-0.658306,0.030761,-0.469886,...,-0.797263,-1.848283,0.390939,0.002834,-0.789122,-1.102753,1.239839,1.605712,-0.660821,-0.698525
24/01/2003,-0.472052,-1.344979,0.0,-0.940321,-2.232757,-0.728177,-0.264227,-0.527970,-1.186240,0.110374,...,-1.774584,-0.150360,0.966999,0.111369,-1.634585,-0.382384,-1.903335,-2.067034,-0.450081,-0.564004
27/01/2003,-0.986913,-2.020038,0.0,-0.688480,-1.482707,0.329981,-1.069488,-0.795302,-0.677945,-0.842492,...,-1.418366,-0.570368,-1.076978,-2.273103,-3.019124,-0.471459,-0.105102,-0.850317,-0.905563,0.059131
28/01/2003,0.283632,-0.120210,0.0,0.071230,0.510474,0.342002,-0.155552,0.616959,0.274994,-0.260207,...,-0.511770,0.577241,-1.431703,0.279284,-1.019027,0.747831,0.751156,0.140598,-0.011911,0.238773
29/01/2003,1.573269,0.391614,0.0,-0.132176,-0.393606,1.243601,-0.156877,1.176021,1.077654,0.600663,...,-0.266210,-0.385630,0.780132,0.863243,0.568011,0.175850,-0.808539,0.662584,-0.225453,1.061641
30/01/2003,0.342692,-1.121887,0.0,-0.082466,0.058422,-0.794554,-0.830296,0.664874,-0.307047,-0.345247,...,0.344269,-0.308601,0.126737,0.414862,-1.530868,-0.329161,1.109419,0.148912,0.060026,-0.142837
31/01/2003,-0.236357,0.163119,0.0,-0.133291,0.519784,0.186739,-0.061219,1.218891,0.650588,1.006731,...,-0.799842,0.848555,1.300889,-0.683101,0.672152,0.402854,-0.239594,0.798560,1.261140,2.053466
03/02/2003,1.152120,0.385988,0.0,0.063827,1.674861,1.171860,0.011082,1.398999,-0.637780,0.451282,...,0.525299,0.510328,-0.261537,0.113919,-0.383597,0.054204,1.100710,-0.653820,0.349018,-0.166528
04/02/2003,-1.449456,-2.527317,0.0,-1.814640,-1.674373,-1.422731,-1.270706,-1.759313,-2.022676,-0.179736,...,1.315124,-1.291353,-0.258692,-1.602175,-2.564680,-2.402559,-1.293278,-1.126741,-1.454556,-1.482116